version: "3.9"
services:
  server:
    build:  ./backend
    command: uvicorn app:app --root-path / --proxy-headers --host 0.0.0.0 --port 8500
    ports: 
    - "8500:8500"
    volumes: 
    - ./backend:/app
    environment: 
      FLASK_ENV: development
  web:
    build: ./frontend
    ports: 
      - "3500:3500"
    # volumes: 
    #   - ./invoice-frontend:/user/src/app
    depends_on: 
      - server